skip the deploy job on job level if no deploy methods are enabled (for now, this is only deploy_cratesio)

diff --git a/.github/workflows/crate_ci.yml b/.github/workflows/crate_ci.yml
--- a/.github/workflows/crate_ci.yml
+++ b/.github/workflows/crate_ci.yml
@@ -221,7 +221,8 @@ jobs:
     if: |
       ((needs.setup.outputs.ci_skip == 'false' || needs.setup.outputs.ci_skip == false) &&
       (needs.setup.outputs.is_pr == 'false' || needs.setup.outputs.is_pr == false) &&
-      (github.event_name == 'push' && github.ref == 'refs/heads/main')) || 
+      (github.event_name == 'push' && github.ref == 'refs/heads/main') &&
+      (inputs.deploy_cratesio == true || inputs.deploy_cratesio == 'true')) || 
       (inputs.force_deploy == true || inputs.force_deploy == 'true')
     steps:
       - name: Init crate workflow
@@ -238,12 +239,12 @@ jobs:
           set -o pipefail
           cargo doc --no-deps
           
-      - name: If no deploy methods enabled, just skip the job
+      - name: If no deploy methods enabled, just fail the job
         run: |
           if [[ ${{ inputs.deploy_cratesio }} == true || ${{ inputs.deploy_cratesio }} == 'true' ]]
           then
-            echo "No deploy methods are enabled, skipping job..."
-            exit 0
+            echo "No deploy methods are enabled, failing job..."
+            exit 1
           fi
           
           
